version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "--- Install Phase ---"
      - apt-get install zip -qq
      - apt-get install jq -qq
  pre_build:
    commands:
      - echo "--- Pre-build Phase ---"
      - python -m venv venv
      - . venv/bin/activate
      - pip install -r src/requirements.txt
      - pip install -r dev-requirements.txt
  build:
    commands:
      - echo "---- Build Phase ----"
      - make debug
      - make lint
  post_build:
    commands:
      - if [ "$BRANCH_NAME" = "main" ]; then export DEPLOY_ACCOUNT_ID=123456789012; else export DEPLOY_ACCOUNT_ID=234567890123; fi
      -  echo "Assuming role in target account $DEPLOY_ACCOUNT_ID "
      -  echo "BRANCH is $BRANCH_NAME"
      -  echo "Deploying the CloudFormation stack"
      - bash ./env.sh














artifacts:
  discard-paths: yes
  files:
    - config.yaml
    - template.yaml
